### ISSUE TITLE
please add ForgeFolia

### ISSUE THREAD

**Issue by kitovoi111** [DeerGiteaMirror/DeerFolia#2]
please add ForgeFolia

**Comment by ColdeZhang** [comment]
First of all, forge is not 'open-source' actually.
Secondary, paper made a lot of modification, that's why mix-server (such as Mohist) are all based on bukkit even not spigot.

So merge forge (or fabric) with paper-like is too complicate to be done. Even someone made it, I'm confidentiliy sure there will be a lot bugs.
